### ISSUE TITLE
US8 - Search Bar

### ISSUE THREAD

**Issue by Hendrik-Pils** [gunsh0tzz/upcycling-app#4]
## Value proposition
As a User:
I want to be able to search through
all ideas
## Description

![Image](https://github.com/gunsh0tzz/upcycling-app/assets/149708083/0080fcac-b433-4bf1-97e3-faeb69b0b358)

## Acceptance criteria
- [ ] On the overview page is a visible
search bar that searches through all
ideas by hashtag

## Tasks
- [ ] create a search-component
- [ ] implement search-queries
- [ ] find a way to implement search bar

**Comment by JuliaSchw** [comment]
hey looks good :) 
how would you like the search bar to function? 
e.g. should the results appear while typing, or after a submit? should the search bar have a dropdown?

so please add some more detailed infos :)

**Comment by Hendrik-Pils** [comment]
We took your suggestions to heart ;)

**Comment by CJAkkuec** [comment]
I'd refer to the user as 'they' not as 'he', but that's a minor change I'll trust you to take care of without requiring another update. 👍
