### ISSUE TITLE
US 6 Navigation

### ISSUE THREAD

**Issue by SarahJoyceMorgen** [gunsh0tzz/upcycling-app#5]
## Value proposition
As a User:
I want to able to navigate quickly
via a Navigationbar

In order to <benefit/purpose>
## Description

![Image](https://github.com/gunsh0tzz/upcycling-app/assets/150039814/c2ae4b87-ab7b-488f-a589-1c6c93a2e04a)

- Precise, no unnecessary information
## Acceptance criteria
- [ ] the navigationbar is visible on the
lading page and the details page 
- [ ]the buttons should navigate to the
corresponding page
## Tasks
- [ ] create a navigation component

**Comment by JuliaSchw** [comment]
looks good! 😊
