### ISSUE TITLE
US4 - Edit

### ISSUE THREAD

**Issue by jore-averbeck** [gunsh0tzz/upcycling-app#7]
## Value proposition
As a User:
I want to edit my ideas
to have an updated version of the 
overview of the idea

## Description
![Image](https://github.com/gunsh0tzz/upcycling-app/assets/149486750/9a365210-be0c-429b-af47-fefb41c86dc0)

## Acceptance criteria
- [ ] Clickable Edit Button that navigates
to the form component with the 
corresponding default Values

## Tasks
- [ ] Create an edit component
- [ ] Create an edit Button
- [ ] make the form page display the
default Value

**Comment by CJAkkuec** [comment]
Hey there, just a few notes:

> As a user
> I want to edit my ideas
> so I can keep them up to date.

The AC and Tasks are very sparse.
Please include the intended behavior of the edit form in the AC (entering values, submission process, etc).
Please also include some more verbose steps as part of the tasks, such as 

> Create an EditButton component
> Create an editing mode for the Form component
> ... etc

**Comment by kevinldg** [comment]
Thx for your feedback @CJAkkuec ! We have updated the user story 👍

**Comment by CJAkkuec** [comment]
> (same page for creating and editing) 

Very strictly speaking - and you can just change it and not post it again for another review - but the user doesn't know when you're reusing a component.

Good job otherwise!
