### ISSUE TITLE
US 7 -

### ISSUE THREAD

**Issue by SarahJoyceMorgen** [gunsh0tzz/upcycling-app#8]
## Value proposition
As a User:
I want to be able to add my favorites
and to view them on an seperate
page

## Description

![Image](https://github.com/gunsh0tzz/upcycling-app/assets/150039814/adda04f4-ef36-417c-ac85-22a8ecff74af)

￼
## Acceptance criteria
- [ ]  clickable favorite Button, that
shows onClick a filled heart
- [ ] The favorites should appear on
the favorites page
- [ ] The navigationbar should link to the
favorites page

## Tasks
Tasks:

- [ ]  create a favorite function
- [ ] make the svg filled onClick
- [ ] create a favorites page with
 all favorite ideas

**Comment by kristinwegener** [comment]
Nice, just one suggestion: you could add that the heart icon is "unfilled", when clicking it again :)

**Comment by jore-averbeck** [comment]
Thanks for the review. We will add your suggestion :)
