### ISSUE TITLE
US11 - Design

### ISSUE THREAD

**Issue by Hendrik-Pils** [gunsh0tzz/upcycling-app#9]
# Value proposition
As a User:
I want to be blown away 
by great design ( to have a good
UX ).

## Acceptance criteria
- [ ] There is a clear design structure
visible throughout the app
- [ ] the design has a high recognition
value.
## Tasks
- [ ] Use AI-Designs for inspiration
- [ ] Create a design concept with figma
- [ ] Create a nice color palette and 
style backgrounds, buttons and 
general elements.
